[package]
name = "zov-ast"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:source.

# internal:crates.
zov-tokens = { workspace = true }
zov-phonemes = { workspace = true }

# external:crates.
