[package]
name = "zov-driver"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:source.

# internal:crates.

# external:crates.
zov-rhymer = { workspace = true }
zov-session = { workspace = true }
