[package]
name = "zov-phonemizer"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:source.

# internal:crates.

# external:crates.

[dependencies.pyo3]
version = "0.24.0"
features = ["auto-initialize"]