[package]
name = "zov-tokenizer"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:source.

# internal:crates.

# external:crates.
zov-reporter = { workspace = true }
zov-tokens = { workspace = true }